import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Toolbar } from '../components/toolbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>YAB Indian Sports News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="page-container">
      <Toolbar />

      <div className={styles.main}>
        <h1><span>Welcome to </span>YAB Indian Sports News</h1>
        <h2>Keep yourself Updated with the Top Indian Sports News!!</h2>
      </div>
    </div>
    </div>
  );
}
